"""phase3a sr_level_confidence_suggestion_acted_at

Revision ID: 000c14406215
Revises: 40958bbbf005
Create Date: 2026-05-11 13:53:12.370895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '000c14406215'
down_revision: Union[str, Sequence[str], None] = '40958bbbf005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence_at_creation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acted_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))

    with op.batch_alter_table('sr_level', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('llm_rationale', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('scored_by_model', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('prompt_version', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sr_level', schema=None) as batch_op:
        batch_op.drop_column('prompt_version')
        batch_op.drop_column('scored_by_model')
        batch_op.drop_column('scored_at')
        batch_op.drop_column('llm_rationale')
        batch_op.drop_column('confidence')

    with op.batch_alter_table('order_suggestion', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('acted_at')
        batch_op.drop_column('confidence_at_creation')

    # ### end Alembic commands ###
