"""phase4.7 order_suggestion context audit cols

Revision ID: 10ca3e83de1e
Revises: 460b4dae04ed
Create Date: 2026-05-26 09:31:24.799313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ca3e83de1e'
down_revision: Union[str, Sequence[str], None] = '460b4dae04ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_qty', sa.Double(), nullable=True))
        batch_op.add_column(sa.Column('size_factor', sa.Double(), server_default='1.0', nullable=False))
        batch_op.add_column(sa.Column('context_note', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_suggestion', schema=None) as batch_op:
        batch_op.drop_column('context_note')
        batch_op.drop_column('size_factor')
        batch_op.drop_column('base_qty')

    # ### end Alembic commands ###
