"""phase2 sr_level order_suggestion

Revision ID: 209df72f33ca
Revises: 0047fb7675f2
Create Date: 2026-05-05 14:45:38.043736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209df72f33ca'
down_revision: Union[str, Sequence[str], None] = '0047fb7675f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_suggestion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Double(), nullable=False),
    sa.Column('limit_price', sa.Double(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_allocation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_of', 'ticker', 'side', name='uq_one_per_ticker_per_week')
    )
    op.create_table('sr_level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Double(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'method', 'as_of', name='uq_sr_per_method_per_day')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sr_level')
    op.drop_table('order_suggestion')
    # ### end Alembic commands ###
