"""phase4.7 weekly_market_context table

Revision ID: 460b4dae04ed
Revises: b735c73212dd
Create Date: 2026-05-26 09:30:56.481558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '460b4dae04ed'
down_revision: Union[str, Sequence[str], None] = 'b735c73212dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_market_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_of', sa.Date(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weekly_market_context', schema=None) as batch_op:
        batch_op.create_index('ix_wmc_week_of', ['week_of'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_market_context', schema=None) as batch_op:
        batch_op.drop_index('ix_wmc_week_of')

    op.drop_table('weekly_market_context')
    # ### end Alembic commands ###
