"""add llm_rationale to order_suggestion

Revision ID: 62b0733b198f
Revises: 10ca3e83de1e
Create Date: 2026-05-27 10:42:40.177976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b0733b198f'
down_revision: Union[str, Sequence[str], None] = '10ca3e83de1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('llm_rationale', sa.Text(), nullable=True))
        batch_op.alter_column('context_note',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_suggestion', schema=None) as batch_op:
        batch_op.alter_column('context_note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('llm_rationale')

    # ### end Alembic commands ###
