"""phase4_order_execution_auto_trade_tables

Revision ID: b735c73212dd
Revises: f2680eed32f8
Create Date: 2026-05-18 11:23:02.743702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b735c73212dd'
down_revision: Union[str, Sequence[str], None] = 'f2680eed32f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_trade_caps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('per_order_max_usd', sa.Double(), nullable=False),
    sa.Column('per_day_max_usd', sa.Double(), nullable=False),
    sa.Column('per_week_max_usd_per_ticker', sa.Double(), nullable=False),
    sa.Column('per_day_max_orders', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_trade_promotion_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('from_mode', sa.String(), nullable=False),
    sa.Column('to_mode', sa.String(), nullable=False),
    sa.Column('broker_scope', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kill_switch_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trigger', sa.String(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('cancelled_order_ids', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suggestion_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('submitted_qty', sa.Double(), nullable=True),
    sa.Column('filled_qty', sa.Double(), nullable=False),
    sa.Column('limit_price', sa.Double(), nullable=True),
    sa.Column('filled_price', sa.Double(), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('client_order_id', sa.String(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('realized_pnl_usd', sa.Double(), nullable=True),
    sa.Column('match_method', sa.String(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_order_id', 'broker', name='uq_broker_order_id')
    )
    with op.batch_alter_table('order_execution', schema=None) as batch_op:
        batch_op.create_index('ix_order_execution_ticker_filled_at', ['ticker', 'filled_at'], unique=False)

    # ### end Alembic commands ###

    # Seed auto_trade_mode = 'OFF' in meta table
    op.execute(sa.text("INSERT OR IGNORE INTO meta (key, value) VALUES ('auto_trade_mode', 'OFF')"))

    # Seed initial conservative auto_trade_caps
    op.execute(sa.text("""
        INSERT INTO auto_trade_caps
        (per_order_max_usd, per_day_max_usd, per_week_max_usd_per_ticker, per_day_max_orders, effective_from)
        VALUES (500, 1500, 1000, 5, datetime('now'))
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_execution', schema=None) as batch_op:
        batch_op.drop_index('ix_order_execution_ticker_filled_at')

    op.drop_table('order_execution')
    op.drop_table('kill_switch_log')
    op.drop_table('auto_trade_promotion_log')
    op.drop_table('auto_trade_caps')
    # ### end Alembic commands ###
