"""phase3b news_event mover_state

Revision ID: e9abd5c02296
Revises: 000c14406215
Create Date: 2026-05-12 19:15:55.036906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9abd5c02296'
down_revision: Union[str, Sequence[str], None] = '000c14406215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mover_state',
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('last_triggered_threshold', sa.Double(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_pct_change', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ticker')
    )
    op.create_table('news_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('headline', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('url_hash', sa.String(), nullable=False),
    sa.Column('llm_material', sa.Boolean(), nullable=True),
    sa.Column('llm_sentiment', sa.String(), nullable=True),
    sa.Column('llm_summary', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('llm_cost_usd', sa.Float(), nullable=True),
    sa.Column('arbitrated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash', name='uq_news_url_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news_event')
    op.drop_table('mover_state')
    # ### end Alembic commands ###
