"""add anchor_method to order_suggestion

Revision ID: f2680eed32f8
Revises: e9abd5c02296
Create Date: 2026-05-16 16:36:56.034354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2680eed32f8'
down_revision: Union[str, Sequence[str], None] = 'e9abd5c02296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkpoints')
    op.drop_table('writes')
    with op.batch_alter_table('order_suggestion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anchor_method', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_suggestion', schema=None) as batch_op:
        batch_op.drop_column('anchor_method')

    op.create_table('writes',
    sa.Column('thread_id', sa.TEXT(), nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), nullable=False),
    sa.Column('task_id', sa.TEXT(), nullable=False),
    sa.Column('idx', sa.INTEGER(), nullable=False),
    sa.Column('channel', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('value', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
    )
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('checkpoint', sa.BLOB(), nullable=True),
    sa.Column('metadata', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    # ### end Alembic commands ###
